# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_packaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='packaging',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
