# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:33
from __future__ import unicode_literals

from django.db import migrations


def add_street_types(apps, schema_editor):
    StreetType = apps.get_model('common', 'StreetType')
    street_types = [
        ('Alley', 'ally.'),
        ('Arcade', 'arc.'),
        ('Avenue', 'ave.'),
        ('Boulevard', 'bvd.'),
        ('Bypass', 'bypa.'),
        ('Circuit', 'cct.'),
        ('Close', 'cl.'),
        ('Corner', 'crn.'),
        ('Court', 'ct.'),
        ('Crescent', 'cres.'),
        ('Drive', 'dr.'),
        ('Esplanade', 'esp.'),
        ('Green', 'grn.'),
        ('Grove', 'gr.'),
        ('Highway', 'hwy.'),
        ('Junction', 'jnc.'),
        ('Lane', 'lane'),
        ('Link', 'link'),
        ('Mews', 'mews'),
        ('Parade', 'pde.'),
        ('Place', 'pl.'),
        ('Ridge', 'rdge.'),
        ('Road', 'rd.'),
        ('Square', 'sq.'),
        ('Street', 'st.'),
        ('Terrace', 'tce.')
    ]
    for full_name, short_name in street_types:
        StreetType.objects.create(
            short_name=short_name,
            full_name=full_name
        )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_street_types)
    ]
