# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20171126_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streettype',
            options={'verbose_name': 'Street type', 'verbose_name_plural': 'Street types'},
        ),
        migrations.AlterField(
            model_name='streettype',
            name='full_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Full name'),
        ),
    ]
