# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:26
from __future__ import unicode_literals

from django.db import migrations


def add_street_types(apps, schema_editor):
    StreetType = apps.get_model('common', 'StreetType')
    street_types = [
        ('Alley', 'ally.', 'Аллея', 'ал.'),
        ('Arcade', 'arc.', 'Аркада', 'арк.'),
        ('Avenue', 'ave.', 'Проспект', 'пр-т.'),
        ('Boulevard', 'bvd.', 'Бульвар', 'бул.'),
        ('Bypass', 'bypa.', 'Об\'їзд', 'об-д'),
        ('Close', 'cl.', 'Тупик', 'туп.'),
        ('Corner', 'crn.', 'Ріг', 'ріг'),
        ('Court', 'ct.', 'Подвір\'я', 'подв.'),
        ('Drive', 'dr.', 'В\'їзд', 'в-зд'),
        ('Esplanade', 'esp.', 'Еспланада', 'есп.'),
        ('Grove', 'gr.', 'Гроув', 'гроув'),
        ('Highway', 'hwy.', 'Шоссе', 'шоссе'),
        ('Junction', 'jnc.', 'Роздоріжжя', 'розд.'),
        ('Lane', 'lane', 'Провулок', 'пров.'),
        ('Ridge', 'rdge.', 'Кряж', 'кряж'),
        ('Road', 'rd.', 'Дорога', 'дор.'),
        ('Square', 'sq.', 'Майдан', 'майд.'),
        ('Street', 'st.', 'Вулиця', 'вул.'),
        ('Terrace', 'tce.', 'Терраса', 'тер.')
    ]
    for full_name, short_name, full_name_uk, short_name_uk in street_types:
        StreetType.objects.create(
            short_name=short_name,
            full_name=full_name,
            short_name_en=short_name,
            full_name_en=full_name,
            short_name_uk=short_name_uk,
            full_name_uk=full_name_uk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_street_types, reverse_code=migrations.RunPython.noop)
    ]
