# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'proxy': True,
                'indexes': [],
            },
            bases=('documents.invoice',),
        ),
    ]
