# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171129_2118'),
        ('documents', '0002_auto_20171129_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='product',
        ),
        migrations.AddField(
            model_name='contract',
            name='products',
            field=models.ManyToManyField(related_name='contracts', to='products.Product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.Customer', verbose_name='Customer'),
        ),
    ]
