# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequirement',
            fields=[
                ('number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Number')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('payment_destination', models.CharField(blank=True, max_length=140, verbose_name='Payment destination')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requirement', to='documents.Invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Payment requirement',
                'verbose_name_plural': 'Payment requirements',
            },
        ),
    ]
