# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_paymentrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequirement',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
